FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /tool

COPY ../data_loss_prevention_tool.py /tool/

RUN pip install --no-cache-dir boto3 requests python-dotenv

CMD ["python", "data_loss_prevention_tool.py"]
