# Generated by Django 5.1 on 2024-08-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataSecurityPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("pattern", models.CharField(max_length=128, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DataLossMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=128)),
                ("text", models.TextField()),
                ("ts", models.CharField(max_length=128)),
                ("channel", models.CharField(max_length=128)),
                ("file_download_link", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "failed_security_patterns",
                    models.ManyToManyField(
                        related_name="messages",
                        to="slack_integration.datasecuritypattern",
                    ),
                ),
            ],
            options={
                "unique_together": {("ts", "channel")},
            },
        ),
    ]
